### ISSUE TITLE
brew audit --strict complains about mlpack formula

### ISSUE THREAD

**Issue by birm** [zoq/homebrew-mlpack#1]
I'm looking into https://github.com/mlpack/mlpack/issues/2108, and following submission guidelines [here](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request), I get the following brew audit problems:
`mlpack:
  * C: 8: col 3: Formulae should not have an `option`
  * C: 19: col 3: dependency "armadillo" (line 19) should be put before dependency "pkg-config" (line 18)
  * C: 20: col 3: dependency "boost" (line 20) should be put before dependency "pkg-config" (line 18)
  * C: 23: col 3: dependency "graphviz" (line 23) should be put before dependency "pkg-config" (line 18)
  * C: 24: col 3: dependency "doxygen" (line 24) should be put before dependency "pkg-config" (line 18)
  * C: 27: col 13: Don't use OS.mac?; Homebrew/core only supports macOS
  * C: 64: col 1: `EOS` is not aligned with `(testpath / "test.cpp").write <<-EOS` or beginning of method definition.`

I'm working on these now, but I thought I'd report anyway :)

**Comment by zoq** [comment]
Thanks, are you planning to open a PR on the homebrew repo?

**Comment by birm** [comment]
yes, I've made one for ensmallen, since it was an easier task  -- https://github.com/Homebrew/homebrew-core/pull/48033

**Comment by zoq** [comment]
Awesome, I think once it merged, we should remove the repo, to avoid any confusion.

**Comment by birm** [comment]
I'm not sure. They may do different things; notably, it looks like homebrew core doesn't allow options. Likewise, there's no nightly (well, we _could_ do nightly, but that may be too many PRs in the homebrew core repo)

**Comment by zoq** [comment]
You are right, don't see an option for the nightly builds, other than doing it in another repo.
